## Perl script to extract 200000 random positions
#cmd:  perl random.pl <ld value file> > <output file name>
# the positions generated by this script will always be different.

#!/usr/bin/perl
  use strict;
  use warnings;
my @tmpArr=();

	my $range = 5703884; ## total no. of SNPs in the file
      #my $range = 29349833;
	my $minimum = 0;
	my $i=0;
	for($i=0;$i<=200000;$i++) { ## 200000 is the number of random positions needed for analysis
		my $random_number = int(rand($range)) + $minimum;
		push(@tmpArr,$random_number);
	}
open myfile,$ARGV[0];

my @file = <myfile>;

for(my $j=0;$j<=$#tmpArr;$j++) {
	my $num = $tmpArr[$j];
	chomp $file[$num];
	print "$file[$num]\n";
	
}
#my $size = scalar(@tmpArr);
#print "$size\n";
